name: ci

on: [push]

jobs:

  ubuntu_check:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3
    - name: Python Linter # see: https://github.com/marketplace/actions/python-linter
      uses: sunnysid3up/python-linter@master

  macos_check:
    name: Build on macOS
    needs: [ubuntu_check]
    runs-on: macos-latest
    steps:
    - run: date

  windows_check:
    name: Build on Windows
    needs: [ubuntu_check]
    runs-on: windows-latest
    steps:
    - run: date
