name: ci

on: [push]

jobs:

  ubuntu_check:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Python Linter # see: https://github.com/marketplace/actions/python-linter
      # You may pin to the exact commit or the version.
      # uses: sunnysid3up/python-linter@93076bd8f740f062069291d738fc70c1b4171c1d
      uses: sunnysid3up/python-linter@v0.1-beta.7

  macos_check:
    name: Build on macOS
    needs: [ubuntu_check]
    runs-on: macos-latest
    steps:
    - run: date

  windows_check:
    name: Build on Windows
    needs: [ubuntu_check]
    runs-on: windows-latest
    steps:
    - run: date
