name: ci

on: [push]

jobs:

  ubuntu_check:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.5.3
      
    - name: Set up Python
      uses: actions/setup-python@v4.7.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Python Linter # see: https://github.com/marketplace/actions/python-linter
      uses: sunnysid3up/python-linter@master
      with:
        pylint-options: "--rcfile=setup.cfg"
        isort-options: "-w 100"

  macos_check:
    name: Build on macOS
    needs: [ubuntu_check]
    runs-on: macos-latest
    steps:
    - run: date

  windows_check:
    name: Build on Windows
    needs: [ubuntu_check]
    runs-on: windows-latest
    steps:
    - run: date
